language: python

matrix:
  include:
    - python: "2.7"
      env:
        - DJANGO_VERSION=>1.4,<1.6
    - python: "2.7"
      env:
        - DJANGO_VERSION=>1.5,<1.7
    - python: "3.3"
      env:
        - DJANGO_VERSION=>1.4,<1.6
    - python: "3.3"
      env:
        - DJANGO_VERSION=>1.5,<1.7


install:
  - pip install django==$DJANGO_VERSION

script:
  - make test
