language: python

python:
  - "2.7"

matrix:
  include:
    - python: "3.3"
      env:
        - DJANGO_VERSION=1.5.5
    - python: "3.3"
      env:
        - DJANGO_VERSION=1.6

env:
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.6

install:
  - pip install django==$DJANGO_VERSION

script:
  - python setup.py develop
  - python setup.py test
